### ISSUE TITLE
DeprecationWarning: fs.Stats constructor is deprecated.

### ISSUE THREAD

**Issue by svivian** [gulp-community/gulp-concat#155]
When running gulp I get this deprecation warning. According to the stack trace it's due to `gulp-concat`. Here's the full error:

```
(node:6586) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at cloneStats (.../node_modules/clone-stats/index.js:6:21)
    at File.clone (.../node_modules/vinyl/index.js:126:24)
    at DestroyableTransform.endStream [as _flush] (.../node_modules/gulp-concat/index.js:84:31)
    at DestroyableTransform.prefinish (.../node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:520:28)
    at DestroyableTransform.emit (node:domain:551:15)
    at prefinish (.../node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (.../node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (.../node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at Writable.end (.../node_modules/readable-stream/lib/_stream_writable.js:594:22)
```

I'm using the latest version of gulp (5.0) and gulp-concat (2.6.1).

**Comment by phated** [comment]
See https://github.com/gulpjs/vinyl-fs/issues/354

**Comment by RickKukiela** [comment]
@phated it seems like vinyl 3.0.1 has dropped clone-stats as a dependency, so updating from Vinyl ^2.0.0 to ^3.0.1 should/may resolve the deprecation warning? Not sure how big of a deal releasing a new version that uses Vinyl 3.0.1 under the hood is though.

**Comment by D4rthR4tz3** [comment]
I guess we won't get an updated version since this issue has been marked as not planned? 👀
